import { useEffect, useState } from "react";
import api from "../../api/axios";
import "../../styles/admin.css";

const Reports = () => {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    const res = await api.get("/reports/payroll");
    setReports(res.data);
  };

  return (
    <div style={{ padding: "30px" }}>
      <h1>Payroll Reports</h1>

      <table border="1" cellPadding="10" style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead>
          <tr>
            <th>Period</th>
            <th>Total Employees</th>
            <th>Generated By</th>
            <th>Generated Date</th>
          </tr>
        </thead>

        <tbody>
          {reports.map((report) => (
            <tr key={report._id}>
              <td>{report.payrollPeriodStart} to {report.payrollPeriodEnd}</td>
              <td>{report.totalEmployees}</td>
              <td>{report.generatedBy?.firstName} {report.generatedBy?.lastName}</td>
              <td>{new Date(report.generatedDate).toLocaleDateString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Reports;