import { useEffect, useState } from "react";
import api from "../../api/axios";
import "../../styles/reports.css";

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(false);

  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);

      const res = await api.get("/reports/payroll");

      const reportList = Array.isArray(res.data)
        ? res.data
        : res.data.reports || res.data.data || [];

      setReports(reportList);
    } catch (error) {
      console.error("Error fetching reports:", error);
      setReports([]);
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (date) => {
    if (!date) return "-";
    return new Date(date).toLocaleDateString();
  };

  const formatMoney = (value) => {
    return `₱${Number(value || 0).toFixed(2)}`;
  };

  const getGeneratedBy = (user) => {
    if (!user) return "Unknown";

    return `${user.firstName || ""} ${user.lastName || ""}`.trim();
  };

  const years = [
    "All",
    ...new Set(
      reports
        .map((report) =>
          new Date(
            report.generatedDate || report.createdAt
          ).getFullYear().toString()
        )
        .filter((year) => year !== "NaN")
    ),
  ];

  const filteredReports = reports.filter((report) => {
    const period = `${
      report.payrollPeriodStart || report.startDate
    } ${report.payrollPeriodEnd || report.endDate}`.toLowerCase();

    const generatedBy = getGeneratedBy(
      report.generatedBy
    ).toLowerCase();

    const matchesSearch =
      period.includes(search.toLowerCase()) ||
      generatedBy.includes(search.toLowerCase());

    const reportYear = new Date(
      report.generatedDate || report.createdAt
    )
      .getFullYear()
      .toString();

    const matchesFilter =
      filter === "All" || reportYear === filter;

    return matchesSearch && matchesFilter;
  });

  return (
    <div className="reports-page">
      <div className="reports-header">
        <div>
          <h1>Payroll Reports</h1>
          <p>
            View generated payroll reports and employee salary breakdowns.
          </p>
        </div>
      </div>

      <div className="reports-card">
        <div className="reports-tools">
          <input
            type="text"
            placeholder="Search by period or generated by..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />

          <select
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
          >
            {years.map((year) => (
              <option key={year} value={year}>
                {year === "All" ? "All Years" : year}
              </option>
            ))}
          </select>
        </div>

        <table>
          <thead>
            <tr>
              <th>Period</th>
              <th>Total Employees</th>
              <th>Generated By</th>
              <th>Generated Date</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            {loading ? (
              <tr>
                <td colSpan="5" className="empty-text">
                  Loading reports...
                </td>
              </tr>
            ) : filteredReports.length > 0 ? (
              filteredReports.map((report) => (
                <tr key={report._id}>
                  <td>
                    {report.payrollPeriodStart ||
                      report.startDate}{" "}
                    to{" "}
                    {report.payrollPeriodEnd ||
                      report.endDate}
                  </td>

                  <td>
                    {report.totalEmployees ||
                      report.employees?.length ||
                      0}
                  </td>

                  <td>
                    {getGeneratedBy(report.generatedBy)}
                  </td>

                  <td>
                    {formatDate(
                      report.generatedDate ||
                        report.createdAt
                    )}
                  </td>

                  <td>
                    <button
                      className="view-report-btn"
                      onClick={() =>
                        setSelectedReport(report)
                      }
                    >
                      View Details
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan="5" className="empty-text">
                  No payroll reports found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {selectedReport && (
        <div className="modal-overlay">
          <div className="report-modal">
            <div className="report-modal-header">
              <div>
                <h2>Payroll Report Details</h2>

                <p>
                  {selectedReport.payrollPeriodStart ||
                    selectedReport.startDate}{" "}
                  to{" "}
                  {selectedReport.payrollPeriodEnd ||
                    selectedReport.endDate}
                </p>
              </div>

              <button
                className="close-report-btn"
                onClick={() => setSelectedReport(null)}
              >
                ×
              </button>
            </div>

            <div className="report-summary">
              <div>
                <span>Total Employees</span>

                <strong>
                  {selectedReport.totalEmployees ||
                    selectedReport.employees?.length ||
                    0}
                </strong>
              </div>

              <div>
                <span>Generated By</span>

                <strong>
                  {getGeneratedBy(
                    selectedReport.generatedBy
                  )}
                </strong>
              </div>

              <div>
                <span>Generated Date</span>

                <strong>
                  {formatDate(
                    selectedReport.generatedDate ||
                      selectedReport.createdAt
                  )}
                </strong>
              </div>
            </div>

            <div className="report-table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Employee</th>
                    <th>Present</th>
                    <th>Late</th>
                    <th>Absent</th>
                    <th>Total Hours</th>
                    <th>Gross Salary</th>
                    <th>Late Deduction</th>
                    <th>Cash Advance</th>
                    <th>Other Deductions</th>
                    <th>Net Salary</th>
                  </tr>
                </thead>

                <tbody>
                  {selectedReport.employees?.length > 0 ? (
                    selectedReport.employees.map(
                      (emp, index) => (
                        <tr key={index}>
                          <td>{emp.employeeName}</td>
                          <td>
                            {emp.totalPresent || 0}
                          </td>
                          <td>{emp.totalLate || 0}</td>
                          <td>
                            {emp.totalAbsent || 0}
                          </td>
                          <td>
                            {emp.totalHours || 0}
                          </td>
                          <td>
                            {formatMoney(
                              emp.grossSalary
                            )}
                          </td>
                          <td>
                            {formatMoney(
                              emp.lateDeductions
                            )}
                          </td>
                          <td>
                            {formatMoney(
                              emp.cashAdvance
                            )}
                          </td>
                          <td>
                            {formatMoney(
                              emp.otherDeductions
                            )}
                          </td>
                          <td>
                            <strong>
                              {formatMoney(
                                emp.netSalary
                              )}
                            </strong>
                          </td>
                        </tr>
                      )
                    )
                  ) : (
                    <tr>
                      <td
                        colSpan="10"
                        className="empty-text"
                      >
                        No employee breakdown found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;